package com.googlecode.aviator.runtime.type.string;

import java.util.Map;
import com.googlecode.aviator.runtime.type.AviatorJavaType;

/**
 * A string segment that generated by a variable in env.
 *
 * @author dennis(killme2008@gmail.com)
 *
 */
public class VarSegment implements StringSegment {
  private final AviatorJavaType var;

  public VarSegment(final String var) {
    super();
    this.var = new AviatorJavaType(var);
  }

  @Override
  public StringBuilder appendTo(final StringBuilder sb, final Map<String, Object> env) {
    return sb.append(this.var.getValue(env));
  }

  @Override
  public String toString() {
    return "VarSegment [var=" + this.var.getName() + "]";
  }
}
